### ISSUE TITLE
CodePilot Can't Work in Version 6.3.2 (6D2105) Of XCode

### ISSUE THREAD

**Issue by chanboo1985** [macoscope/CodePilot#42] opened 2015-05-25 09:32 UTC
if inscribe。
before can use。
but ，after the upgrade xcode and osx，codepilot can't work.
please resolve this issues,thanks!

**Comment by bartekchlebek** [comment] 2015-05-25 10:04
Please have a look at #40 and let us know if it appears to be the same problem you have. Thanks!

**Comment by chanboo1985** [comment] 2015-05-25 11:01
yes,it appears to be the same problem. Has had the similar pop-up message before, but not today, use shortcuts CMD + shift + x without any hints

**Comment by bartekchlebek** [comment] 2015-05-25 12:37
Duplicate of #40

**Closed by bartekchlebek** 2015-05-25 12:37 UTC
Labels: bug, duplicate
