### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by revolter** [macoscope/CodePilot#51] opened 2015-07-10 11:28 UTC
I installed this via `Alcatraz`, the plugin __is__ in the `Plug-ins` directory, but the shortcut does nothing.

**Comment by coreydaley** [comment] 2015-07-10 20:49
Having the same issue.

**Comment by bartekchlebek** [comment] 2015-07-17 07:31
Duplicate of #47

**Closed by bartekchlebek** 2015-07-17 07:31 UTC
Labels: duplicate
